@php($editing = isset($product))
<form method="POST" action="{{ $editing ? route('admin.products.update', $product) : route('admin.products.store') }}" enctype="multipart/form-data" novalidate class="space-y-6" x-data="{ submitting: false, dirty: false, coverName: '', fileName: '' }" x-on:change="dirty = true" x-on:submit="submitting = true; dirty = false" x-on:beforeunload.window="if (dirty) $event.preventDefault()">
    @csrf @if($editing) @method('PUT') @endif
    <div><x-input-label for="title" value="Título" /><x-text-input id="title" name="title" type="text" class="w-full" :value="old('title', $product->title ?? '')" required aria-describedby="title-error" :aria-invalid="$errors->has('title') ? 'true' : 'false'" /><x-input-error id="title-error" :messages="$errors->get('title')" class="mt-2" /></div>
    <div><x-input-label for="description" value="Descrição" /><textarea id="description" name="description" rows="7" required aria-describedby="description-error" aria-invalid="{{ $errors->has('description') ? 'true' : 'false' }}" class="field resize-none">{{ old('description', $product->description ?? '') }}</textarea><x-input-error id="description-error" :messages="$errors->get('description')" class="mt-2" /></div>
    <div class="grid gap-6 sm:grid-cols-2"><div><x-input-label for="price" value="Preço em reais" /><x-text-input id="price" name="price" type="number" min="0.01" max="99999999.99" step="0.01" class="w-full" :value="old('price', $product->price ?? '')" required aria-describedby="price-hint price-error" :aria-invalid="$errors->has('price') ? 'true' : 'false'" /><p id="price-hint" class="mt-1 text-xs text-slate-500">Use até duas casas decimais.</p><x-input-error id="price-error" :messages="$errors->get('price')" class="mt-2" /></div><label class="mt-6 flex min-h-12 items-center gap-3 rounded-xl border border-slate-300 px-4"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product->is_active ?? true)) class="rounded border-slate-300 text-blue-600 focus:ring-blue-500"><span class="text-sm font-semibold">Produto ativo na vitrine</span></label></div>
    <div class="grid gap-6 sm:grid-cols-2"><div><x-input-label for="cover" value="Imagem de capa" /><input id="cover" name="cover" type="file" accept="image/jpeg,image/png,image/webp" class="field text-sm" x-on:change="coverName = $event.target.files[0]?.name || ''" aria-describedby="cover-hint cover-error" aria-invalid="{{ $errors->has('cover') ? 'true' : 'false' }}"><p id="cover-hint" class="mt-1 text-xs text-slate-500" x-text="coverName || 'JPG, PNG ou WebP · máximo 4 MB'"></p><x-input-error id="cover-error" :messages="$errors->get('cover')" class="mt-2" /></div><div><x-input-label for="file" value="Arquivo do produto" /><input id="file" name="file" type="file" @required(!$editing) accept=".zip,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx" class="field text-sm" x-on:change="fileName = $event.target.files[0]?.name || ''" aria-describedby="file-hint file-error" aria-invalid="{{ $errors->has('file') ? 'true' : 'false' }}"><p id="file-hint" class="mt-1 text-xs text-slate-500" x-text="fileName || '{{ $editing ? 'Envie somente para substituir · ' : '' }}ZIP, PDF ou documento · máximo 100 MB'"></p><x-input-error id="file-error" :messages="$errors->get('file')" class="mt-2" /></div></div>
    <div class="flex flex-col-reverse gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:justify-end"><a href="{{ route('admin.products.index') }}" class="btn-secondary">Cancelar</a><button type="submit" class="btn-primary" :disabled="submitting"><span x-show="!submitting">{{ $editing ? 'Salvar alterações' : 'Criar produto' }}</span><span x-show="submitting" x-cloak>Enviando…</span></button></div>
</form>
