<x-app-layout>
    <x-slot:title>Produtos</x-slot:title>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="eyebrow">Catálogo</p><h1 class="mt-1 font-display text-2xl font-bold">Produtos</h1></div><a href="{{ route('admin.products.create') }}" class="btn-primary">Novo produto</a></div></x-slot>
    <div class="page-container py-8"><section class="panel overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Produto</th><th class="px-5 py-3">Preço</th><th class="px-5 py-3">Disponibilidade</th><th class="px-5 py-3 text-right">Ações</th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($products as $product)<tr><td class="px-5 py-4"><div class="flex items-center gap-3">@if($product->cover_path)<img src="{{ asset($product->cover_path) }}" alt="" class="h-12 w-16 rounded-lg object-cover">@else<div class="grid h-12 w-16 place-items-center rounded-lg bg-slate-100 text-slate-400">KL</div>@endif<div><p class="font-bold text-slate-900">{{ $product->title }}</p><p class="font-mono text-xs text-slate-500">{{ $product->slug }}</p></div></div></td><td class="px-5 py-4 font-semibold">R$ {{ number_format((float) $product->price, 2, ',', '.') }}</td><td class="px-5 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold {{ $product->is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-700' }}">{{ $product->is_active ? 'Ativo' : 'Inativo' }}</span></td><td class="px-5 py-4 text-right"><div class="flex justify-end gap-2"><a class="btn-secondary" href="{{ route('admin.products.edit', $product) }}">Editar</a><button type="button" class="min-h-11 rounded-xl px-3 text-sm font-bold text-red-700 hover:bg-red-50" x-data x-on:click.prevent="$dispatch('open-modal', 'archive-product-{{ $product->id }}')">Arquivar</button></div>
        <x-modal name="archive-product-{{ $product->id }}" focusable maxWidth="md"><div class="p-6"><p class="eyebrow text-red-700">Confirmar ação</p><h2 class="mt-2 font-display text-xl font-bold">Arquivar {{ $product->title }}?</h2><p class="mt-3 text-sm text-slate-600">O produto sai da vitrine. Clientes que já pagaram continuam com acesso ao download.</p><form method="POST" action="{{ route('admin.products.destroy', $product) }}" class="mt-6 flex justify-end gap-3" novalidate>@csrf @method('DELETE')<x-secondary-button x-on:click="$dispatch('close')">Cancelar</x-secondary-button><x-danger-button>Arquivar produto</x-danger-button></form></div></x-modal></td></tr>
        @empty<tr><td colspan="4" class="px-5 py-14 text-center"><p class="font-bold text-slate-800">Seu catálogo ainda está vazio.</p><a href="{{ route('admin.products.create') }}" class="mt-2 inline-block text-sm font-bold text-blue-700">Cadastrar o primeiro produto</a></td></tr>@endforelse
        </tbody></table></div></section><div class="mt-6">{{ $products->links() }}</div></div>
</x-app-layout>
